IMAGE_NAME = "ubuntu/xenial64"

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 8192 # required to host confluent helm chart

    config.vm.network "forwarded_port", guest: 5000, host: 5000
    end

    config.vm.define "ubuntu-box" do |k8s|
        k8s.vm.box = IMAGE_NAME

        k8s.vm.provision "ansible" do |ansible|
            ansible.playbook = "provision_box/playbook.yml"
        end
    end
end
