---

- hosts: all
  become: true

  tasks:
  - name: Install packages that allow apt to be used over HTTPS and pip/dev dependencies
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop:
      - apt-transport-https
      - ca-certificates
      - python3-pip
      - python3-setuptools

  - name: Install Git
    package:
      name:
        - git
      state: present
    become: True

  - name: Upgrade pip3
    shell: pip3 install --upgrade pip && pip3 --version

  - name: Add apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add apt respository for stable version of Docker
    shell: |
      add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      apt-get update

  - name: Install Docker
    apt:
      name: docker-ce
      state: present
      update_cache: yes

  - name: Add vagrant user to docker group
    shell: sudo usermod -aG docker vagrant

  - name: Add apt signing key for Kubectl
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Add apt repo for kubectl
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present

  - name: Install kubectl
    apt:
      name: kubectl
      state: present
      update_cache: yes

  - name: Install minikube
    shell: |
      curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
      chmod +x minikube
      mkdir -p /usr/local/bin/
      install minikube /usr/local/bin/

  - name: Start minikube
    shell: minikube start --driver=docker
    become: true
    become_user: vagrant

  - name: Verify status of cluster
    shell: minikube status
    become: true
    become_user: vagrant

  - name: Ensure pyhelm is installed
    pip:
      name:
        - pyhelm
      extra_args: --ignore-installed requests
      state: present

  - name: Install older version of requests for pyhelm
    pip:
      name:
        - requests==2.14.2
      state: present

  - name: Ensure pyhelm is installed.
    pip:
      name:
        - pyhelm
      state: present

  - name: Install Helm
    shell: |
      curl https://helm.baltorepo.com/organization/signing.asc | apt-key add -
      echo "deb https://baltocdn.com/helm/stable/debian/ all main" | tee /etc/apt/sources.list.d/helm-stable-debian.list
      apt-get update
      apt-get install helm

  - name: Add apt signing key for Helm
    apt_key:
      url:  https://helm.baltorepo.com/organization/signing.asc
      state: present

  - name: Add apt repository for stable version of Helm
    apt_repository:
      repo: deb https://baltocdn.com/helm/stable/debian/ all main
      state: present

  - name: Install Helm
    apt:
      name: helm
      state: present
      update_cache: yes

  - name: Install Helm Charts from git repo
    shell: helm repo add confluentinc https://confluentinc.github.io/cp-helm-charts/
    become: true
    become_user: vagrant

  - name: Helm repo update
    shell: helm repo update
    become: true
    become_user: vagrant

  - name: Install charts
    shell: helm install my-confluent confluentinc/cp-helm-charts --version 0.5.0
    become: true
    become_user: vagrant

  - name: Copy web application to guest
    copy:
      src: ../../datetime-injector-app
      dest: /app

  - name: Copy web application kubernetes deployment to guest
    copy:
      src: ../../kubernetes/deployments
      dest: /app

  - name: Build docker image to minikubes docker registry
    shell: |
      eval $(minikube -p minikube docker-env)
      docker build /app/datetime-injector-app -t datetime-injector-app:0.3
    become: true
    become_user: vagrant

  - name: Deploy datetime-injector-app to minikube cluster
    shell: kubectl create -f /app/deployments/datetime-injector-app.yml
    become: true
    become_user: vagrant
